# This is a basic workflow to help you get started with Actions

name: 'Check Branch'

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check branch
        if: github.base_ref == 'master' && github.head_ref != 'dev'
        run: |
          echo "Permission error: Cannot merge onto master from branch other than dev"
          exit 1
